### PR TITLE
fix: spelling error in button

### PR DESCRIPTION
**Pull request by tamm**
button was misspelled with three t

### CODE REVIEW

**Review by lukebennett88 — APPROVED** [review]

**Review by lukebennett88 — CHANGES_REQUESTED** [review]
Good catch, thanks @tamm.
Technically this is a patch, are you able to create a new changeset 🙏
(All you need to do is run `yarn changeset` and follow the prompts in the CLI)

**Review by freemany — APPROVED** [review]

**Comment by JedWatson** [comment]
@tamm or alternatively, the _even easier_ way to add a changeset is to use the [link](https://github.com/brighte-labs/spark-web/new/fix-spelling-error-in-button?filename=.changeset/old-carrots-compete.md&value=---%0A%22%40spark-web%2Fbutton%22%3A%20patch%0A---%0A%0Afix%3A%20spelling%20error%20in%20button%0A) in the Changeset Bot's comment above

**Review by nderkim — APPROVED** [review]

**Comment by tamm** [comment]
@lukebennett88 and @JedWatson I've pushed a changeset!

**Review by lukebennett88 — APPROVED** [review]
LGTM 👍
Thanks @tamm 🎉

**Pull request merged**
